# Workflow to publish Godot HTML5 games to GitHub Pages and Itch.io

# Make sure your project is configured for Web export
# to the path `build/web`.

name: "Publish to Web"

env:
  GODOT_VERSION: 4.2.1 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
      - name: Zip files for Itch
        uses: vimtor/action-zip@v1.1
        with:
          files: build/web/
          dest: build/web.zip
      - name: Deploy to Itch with Butler
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
          itch_user: ExodusIV
          itch_game: geometry-survival
          version: ${{ github.ref_name }}
          files: |
            web build/web.zip
